#!/usr/bin/env bash
set -euo pipefail

# PREVIEW ONLY: this script is intentionally disabled.
# It must not delete anything unless a human manually edits it later.
# No deletion commands are active in this file.

echo "PREVIEW ONLY: no repositories will be deleted."
echo "This script is intentionally disabled. Edit manually only after a separate final confirmation."
exit 0

# The commands below are commented out on purpose.
# To use them in the future, you would need to manually review, edit, uncomment, and run them yourself.

# gh repo delete Ibraheemolasupogit/A2A-MCP-ADK-Integration --yes
# gh repo delete Ibraheemolasupogit/a2a-python --yes
# gh repo delete Ibraheemolasupogit/a2a-samples --yes
# gh repo delete Ibraheemolasupogit/ab-testing-at-edge --yes
# gh repo delete Ibraheemolasupogit/academicpages.github.io --yes
# gh repo delete Ibraheemolasupogit/Academind-react-complete-guide-code --yes
# gh repo delete Ibraheemolasupogit/Accelerate-Agentic-AI-DW-200-Agentic --yes
# gh repo delete Ibraheemolasupogit/Accident-and-Emergency-A-E-Forecasting --yes
# gh repo delete Ibraheemolasupogit/agent-framework --yes
# gh repo delete Ibraheemolasupogit/agent-innovator-lab --yes
# gh repo delete Ibraheemolasupogit/agentic-ai-lab-foundry --yes
# gh repo delete Ibraheemolasupogit/AI-102-AIEngineer --yes
# gh repo delete Ibraheemolasupogit/ai-agents-for-beginners --yes
# gh repo delete Ibraheemolasupogit/AI-For-Beginners --yes
# gh repo delete Ibraheemolasupogit/ai-gov-uk-website --yes
# gh repo delete Ibraheemolasupogit/ai-infra-cluster-provisioning --yes
# gh repo delete Ibraheemolasupogit/ai-platform-samples --yes
# gh repo delete Ibraheemolasupogit/AI-PredictiveMaintenance --yes
# gh repo delete Ibraheemolasupogit/Air-Passenger-Count-Prediction-Aircraft --yes
# gh repo delete Ibraheemolasupogit/Air-traffic-atdelay-Aircraft --yes
# gh repo delete Ibraheemolasupogit/ALZ-Bicep --yes
# gh repo delete Ibraheemolasupogit/amazon-bedrock-agents-healthcare-lifesciences --yes
# gh repo delete Ibraheemolasupogit/amazon-bedrock-rag --yes
# gh repo delete Ibraheemolasupogit/amazon-bedrock-samples --yes
# gh repo delete Ibraheemolasupogit/amazon-codewhisperer-workshop --yes
# gh repo delete Ibraheemolasupogit/amazon-dynamodb-labs --yes
# gh repo delete Ibraheemolasupogit/amazon-ec2-nice-dcv-semiconductor-wafer-data_MATLAB --yes
# gh repo delete Ibraheemolasupogit/amazon-mlops-example-tensorflow --yes
# gh repo delete Ibraheemolasupogit/amazon-mwaa-examples --yes
# gh repo delete Ibraheemolasupogit/amazon-nova-samples --yes
# gh repo delete Ibraheemolasupogit/amazon-personalize-samples --yes
# gh repo delete Ibraheemolasupogit/amazon-redshift-udfs --yes
# gh repo delete Ibraheemolasupogit/amazon-rekognition-virtual-proctor --yes
# gh repo delete Ibraheemolasupogit/amazon-sagemaker-ab-testing-pipeline --yes
# gh repo delete Ibraheemolasupogit/amazon-sagemaker-examples --yes
# gh repo delete Ibraheemolasupogit/amazon-sagemaker-generativeai --yes
# gh repo delete Ibraheemolasupogit/amazon-sagemaker-predictive-maintenance --yes
# gh repo delete Ibraheemolasupogit/amazon-textract-textractor --yes
# gh repo delete Ibraheemolasupogit/amazon-transcribe-live-call-analytics --yes
# gh repo delete Ibraheemolasupogit/Amazon-Translate-document-translation --yes
# gh repo delete Ibraheemolasupogit/ambulance_response_times_and_handover_delays --yes
# gh repo delete Ibraheemolasupogit/ambulance-DES --yes
# gh repo delete Ibraheemolasupogit/analytical-data-style-guide-SW --yes
# gh repo delete Ibraheemolasupogit/ansible --yes
# gh repo delete Ibraheemolasupogit/Apache-airflow --yes
# gh repo delete Ibraheemolasupogit/Apache-arrow --yes
# gh repo delete Ibraheemolasupogit/Apache-flink --yes
# gh repo delete Ibraheemolasupogit/Apache-hadoop --yes
# gh repo delete Ibraheemolasupogit/Apache-kafka --yes
# gh repo delete Ibraheemolasupogit/Apache-superset --yes
# gh repo delete Ibraheemolasupogit/APL-2002-develop-aspnet-core-consumes-api --yes
# gh repo delete Ibraheemolasupogit/AppliedNLPMaterial --yes
# gh repo delete Ibraheemolasupogit/atomic-red-team --yes
# gh repo delete Ibraheemolasupogit/attendance_system --yes
# gh repo delete Ibraheemolasupogit/au-azure-databricks-cicd --yes
# gh repo delete Ibraheemolasupogit/autogen --yes
# gh repo delete Ibraheemolasupogit/autoscaler --yes
# gh repo delete Ibraheemolasupogit/awesome-ai-agents --yes
# gh repo delete Ibraheemolasupogit/awesome-ml-for-cybersecurity --yes
# gh repo delete Ibraheemolasupogit/aws-fraud-detector-samples --yes
# gh repo delete Ibraheemolasupogit/aws-lex-web-ui --yes
# gh repo delete Ibraheemolasupogit/aws-machine-learning-university-accelerated-nlp --yes
# gh repo delete Ibraheemolasupogit/aws-machine-learning-university-Decision-Trees-and-Ensemble-Methods-Class --yes
# gh repo delete Ibraheemolasupogit/aws-saa-c03 --yes
# gh repo delete Ibraheemolasupogit/aws-serverless-airline-booking --yes
# gh repo delete Ibraheemolasupogit/aws-serverless-nlp-comprehend-using-aws-cdk --yes
# gh repo delete Ibraheemolasupogit/AZ-1008-Administer-Active-Directory-Domain-Services --yes
# gh repo delete Ibraheemolasupogit/AZ-104-MicrosoftAzureAdministrator --yes
# gh repo delete Ibraheemolasupogit/az-2003-deploy-cloud-native-applications-using-azure-container-apps --yes
# gh repo delete Ibraheemolasupogit/AZ-2006-automate-azure-loadtesting-github-actions --yes
# gh repo delete Ibraheemolasupogit/AZ-2007-Accelerate-app-development-by-using-GitHub-Copilot --yes
# gh repo delete Ibraheemolasupogit/AZ-204-DevelopingSolutionsforMicrosoftAzure-Devops-Prereq --yes
# gh repo delete Ibraheemolasupogit/az-204-examples --yes
# gh repo delete Ibraheemolasupogit/AZ-305-DesigningMicrosoftAzureInfrastructureSolutions --yes
# gh repo delete Ibraheemolasupogit/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions --yes
# gh repo delete Ibraheemolasupogit/AZ500-AzureSecurityTechnologies --yes
# gh repo delete Ibraheemolasupogit/azure-ai-agent-lab --yes
# gh repo delete Ibraheemolasupogit/azure-ai-agents-labs-Agentic-RAG --yes
# gh repo delete Ibraheemolasupogit/azure-devops-mcp --yes
# gh repo delete Ibraheemolasupogit/Azure-load-testing --yes
# gh repo delete Ibraheemolasupogit/Azure-Machine-Learning-Practice-GuidesML-Practice-Guides --yes
# gh repo delete Ibraheemolasupogit/azure-monitor-baseline-alerts --yes
# gh repo delete Ibraheemolasupogit/azure-powershell --yes
# gh repo delete Ibraheemolasupogit/azure-search-knowledge-mining --yes
# gh repo delete Ibraheemolasupogit/Azure-Sentinel --yes
# gh repo delete Ibraheemolasupogit/azure-service-bus --yes
# gh repo delete Ibraheemolasupogit/azure-service-bus-emulator-installer --yes
# gh repo delete Ibraheemolasupogit/azureml-examples --yes
# gh repo delete Ibraheemolasupogit/bedrock-access-gateway-API --yes
# gh repo delete Ibraheemolasupogit/bedrock-engineer --yes
# gh repo delete Ibraheemolasupogit/browser-use --yes
# gh repo delete Ibraheemolasupogit/build-push-action --yes
# gh repo delete Ibraheemolasupogit/Building-and-Deploying-Machine-Learning-Solutions-with-Vertex-AI-Challenge-Lab --yes
# gh repo delete Ibraheemolasupogit/buildx --yes
# gh repo delete Ibraheemolasupogit/chocolate-ai --yes
# gh repo delete Ibraheemolasupogit/clean-code-course-code --yes
# gh repo delete Ibraheemolasupogit/cli --yes
# gh repo delete Ibraheemolasupogit/clinical-risk-stratification --yes
# gh repo delete Ibraheemolasupogit/cloud-build-samples --yes
# gh repo delete Ibraheemolasupogit/Co-Pilot-build-applications-w-copilot-agent-mode --yes
# gh repo delete Ibraheemolasupogit/code-contributions --yes
# gh repo delete Ibraheemolasupogit/Cognitive-Services-Vision-Solution-Templates --yes
# gh repo delete Ibraheemolasupogit/community --yes
# gh repo delete Ibraheemolasupogit/compose --yes
# gh repo delete Ibraheemolasupogit/composer-airflow --yes
# gh repo delete Ibraheemolasupogit/computer-vision-aws-machine-learning-university-accelerated-cv --yes
# gh repo delete Ibraheemolasupogit/Configure-secure-access-to-workloads-with-Azure-virtual-networking-services --yes
# gh repo delete Ibraheemolasupogit/configure-siem-security-operations-using-microsoft-sentinel --yes
# gh repo delete Ibraheemolasupogit/configuring-qbusiness-with-idc-tti --yes
# gh repo delete Ibraheemolasupogit/contoso-chat-csharp-prompty --yes
# gh repo delete Ibraheemolasupogit/course-deep-learning-bootcamp --yes
# gh repo delete Ibraheemolasupogit/course-master-big-data-with-pyspark-and-aws-Lex --yes
# gh repo delete Ibraheemolasupogit/course-ml-projects --yes
# gh repo delete Ibraheemolasupogit/course-pytorch --yes
# gh repo delete Ibraheemolasupogit/Credit-Card-Application-Fraud-Analytics --yes
# gh repo delete Ibraheemolasupogit/Credit-card-approval-prediction-classification --yes
# gh repo delete Ibraheemolasupogit/Credit-Card-Fraud-Detection --yes
# gh repo delete Ibraheemolasupogit/Credit-Card-Fraud-Detection-using-Autoencoders-in-Keras --yes
# gh repo delete Ibraheemolasupogit/Credit-Risk-Modeling-End-to-End-Project --yes
# gh repo delete Ibraheemolasupogit/crewAI --yes
# gh repo delete Ibraheemolasupogit/DALL-E --yes
# gh repo delete Ibraheemolasupogit/darkspace-Git-Hub-GH-900 --yes
# gh repo delete Ibraheemolasupogit/data-analytics-golden-demo --yes
# gh repo delete Ibraheemolasupogit/data-analytics-services --yes
# gh repo delete Ibraheemolasupogit/data-api-builder --yes
# gh repo delete Ibraheemolasupogit/data-beans --yes
# gh repo delete Ibraheemolasupogit/Data-pipeline-project --yes
# gh repo delete Ibraheemolasupogit/Data-Science-For-Beginners --yes
# gh repo delete Ibraheemolasupogit/data-science-interviews --yes
# gh repo delete Ibraheemolasupogit/data-science-ipython-notebooks --yes
# gh repo delete Ibraheemolasupogit/datascience --yes
# gh repo delete Ibraheemolasupogit/Deep-Live-Cam-GAN --yes
# gh repo delete Ibraheemolasupogit/Defend-against-cyberthreats-Microsoft-Defender-XDR --yes
# gh repo delete Ibraheemolasupogit/Defender-SC-200T00A-Microsoft-Security-Operations-Analyst --yes
# gh repo delete Ibraheemolasupogit/delta --yes
# gh repo delete Ibraheemolasupogit/deploy-cloud-functions --yes
# gh repo delete Ibraheemolasupogit/Develop-generative-AI-apps-in-Azures-GenAIOps --yes
# gh repo delete Ibraheemolasupogit/Devops-AZ400-DesigningandImplementingMicrosoftDevOpsSolutions --yes
# gh repo delete Ibraheemolasupogit/Devops-eShopOnWeb --yes
# gh repo delete Ibraheemolasupogit/Devops-hello-world --yes
# gh repo delete Ibraheemolasupogit/DevOps-solutions --yes
# gh repo delete Ibraheemolasupogit/diffusers --yes
# gh repo delete Ibraheemolasupogit/dify --yes
# gh repo delete Ibraheemolasupogit/docs --yes
# gh repo delete Ibraheemolasupogit/DP-100-Designing-and-implementing-data-science-solutions-on-Azure --yes
# gh repo delete Ibraheemolasupogit/dp-203-azure-data-engineer-DP-3012-Data-Analytics-Solution-with-Azure-Synapse-Analytics --yes
# gh repo delete Ibraheemolasupogit/dp-300-database-administrator --yes
# gh repo delete Ibraheemolasupogit/DP-3028-Gen-AI-Eng-DP-3014-ML-solution-with-Azure-Databricks-DP-3011-Data-Analytic-DP-3027-Data-DEgr --yes
# gh repo delete Ibraheemolasupogit/dp-420-cosmos-db-dev --yes
# gh repo delete Ibraheemolasupogit/DP-500-Azure-Data-Analyst --yes
# gh repo delete Ibraheemolasupogit/DP-700T00-A-Microsoft-Fabric-Data-Engineer-Fabric-mslearn-fabric --yes
# gh repo delete Ibraheemolasupogit/DP-750T00-Implement-Data-Engineering-Solutions-using-Azure-Databricks --yes
# gh repo delete Ibraheemolasupogit/DP-900T00A-Azure-Data-Fundamentals --yes
# gh repo delete Ibraheemolasupogit/End-to-End-Vertex-AI-Pipeline-for-Fraud-Detection --yes
# gh repo delete Ibraheemolasupogit/fabric-cli-powerbi-cicd-sample --yes
# gh repo delete Ibraheemolasupogit/Forecasting --yes
# gh repo delete Ibraheemolasupogit/Fraud-Analytics-with-AI-ML --yes
# gh repo delete Ibraheemolasupogit/fraud-detection-handbook --yes
# gh repo delete Ibraheemolasupogit/GCP-deploy-cloudrun --yes
# gh repo delete Ibraheemolasupogit/GCP-example-workflows --yes
# gh repo delete Ibraheemolasupogit/gcp-mlops-development-to-deployment --yes
# gh repo delete Ibraheemolasupogit/GCP-workflows-demos --yes
# gh repo delete Ibraheemolasupogit/gcs-connector-for-pytorch --yes
# gh repo delete Ibraheemolasupogit/gemini-cli --yes
# gh repo delete Ibraheemolasupogit/genai-cookbook --yes
# gh repo delete Ibraheemolasupogit/generative-ai --yes
# gh repo delete Ibraheemolasupogit/gensim --yes
# gh repo delete Ibraheemolasupogit/Get-started-Microsoft-Entra-Management-Tasks --yes
# gh repo delete Ibraheemolasupogit/getting-started-with-github-copilot --yes
# gh repo delete Ibraheemolasupogit/Git-Hub-Actions-cache --yes
# gh repo delete Ibraheemolasupogit/Git-Hub-Actions-download-artifact --yes
# gh repo delete Ibraheemolasupogit/Git-Hub-Actions-JavaScript-toolkit --yes
# gh repo delete Ibraheemolasupogit/Git-Hub-Actions-runner-images --yes
# gh repo delete Ibraheemolasupogit/Git-Hub-Actions-upload-artifact --yes
# gh repo delete Ibraheemolasupogit/GitHub-actions-checkout --yes
# gh repo delete Ibraheemolasupogit/GitHub-Actions-setup-node --yes
# gh repo delete Ibraheemolasupogit/GitHub-actions-starter-workflows --yes
# gh repo delete Ibraheemolasupogit/google-cloud-certifications --yes
# gh repo delete Ibraheemolasupogit/GoogleCloudSkillsboost --yes
# gh repo delete Ibraheemolasupogit/Guide-on-making-contribution --yes
# gh repo delete Ibraheemolasupogit/Gurobi-Modeling-examples --yes
# gh repo delete Ibraheemolasupogit/GurobiExamples --yes
# gh repo delete Ibraheemolasupogit/Health-Data-and-AI-Blueprint --yes
# gh repo delete Ibraheemolasupogit/hello-github-actions_GitHub_MS --yes
# gh repo delete Ibraheemolasupogit/hive --yes
# gh repo delete Ibraheemolasupogit/House-Prices-Advanced-Regression-Techniques-Kaggle --yes
# gh repo delete Ibraheemolasupogit/implement-column-level-encryption-in-amazon-redshift-with-aws-glue-and-aws-lambda-udf --yes
# gh repo delete Ibraheemolasupogit/implement-security-through-pipeline-using-devops --yes
# gh repo delete Ibraheemolasupogit/introduction-to-github --yes
# gh repo delete Ibraheemolasupogit/JetStream --yes
# gh repo delete Ibraheemolasupogit/kafka-tutorials --yes
# gh repo delete Ibraheemolasupogit/kops --yes
# gh repo delete Ibraheemolasupogit/kubeflow-gke-docs --yes
# gh repo delete Ibraheemolasupogit/kubernetes --yes
# gh repo delete Ibraheemolasupogit/kubernetes-engine-samples --yes
# gh repo delete Ibraheemolasupogit/labs-ai-tools-for-devs --yes
# gh repo delete Ibraheemolasupogit/langchain --yes
# gh repo delete Ibraheemolasupogit/langflow --yes
# gh repo delete Ibraheemolasupogit/langgraph --yes
# gh repo delete Ibraheemolasupogit/lda-NLP --yes
# gh repo delete Ibraheemolasupogit/Loan-prediction-using-Machine-Learning-and-Python --yes
# gh repo delete Ibraheemolasupogit/login-action --yes
# gh repo delete Ibraheemolasupogit/MachineLearningNotebooks --yes
# gh repo delete Ibraheemolasupogit/MachineLearningSamples-PredictiveMaintenance --yes
# gh repo delete Ibraheemolasupogit/MB-800-Business-Central-Functional-Consultant --yes
# gh repo delete Ibraheemolasupogit/MD-102T00-Microsoft-365-Endpoint-Administrator --yes
# gh repo delete Ibraheemolasupogit/MetaGPT --yes
# gh repo delete Ibraheemolasupogit/Microsoft-Courses --yes
# gh repo delete Ibraheemolasupogit/Microsoft-Fabric-project-by-Microsoft --yes
# gh repo delete Ibraheemolasupogit/Microsoft-SQL-Server-Documentations --yes
# gh repo delete Ibraheemolasupogit/ML-For-Beginners --yes
# gh repo delete Ibraheemolasupogit/ml-on-gcp --yes
# gh repo delete Ibraheemolasupogit/MLOps-model-deployment-GCP --yes
# gh repo delete Ibraheemolasupogit/mlops-stacks --yes
# gh repo delete Ibraheemolasupogit/mlops-templates --yes
# gh repo delete Ibraheemolasupogit/MLOps-v2 --yes
# gh repo delete Ibraheemolasupogit/mlops-with-vertex-ai --yes
# gh repo delete Ibraheemolasupogit/mlsecops --yes
# gh repo delete Ibraheemolasupogit/MS-102T00-Microsoft-365-Administrator-Essentials --yes
# gh repo delete Ibraheemolasupogit/MS-4002-Prepare-security-and-compliance-to-support-Microsoft-365-Copilot --yes
# gh repo delete Ibraheemolasupogit/MS-4010-Extend-Microsoft365-Copilot-declarative-agents-VS-Code --yes
# gh repo delete Ibraheemolasupogit/MS-700-Managing-Microsoft-Teams --yes
# gh repo delete Ibraheemolasupogit/MS-900T01-Microsoft-365-Fundamentals --yes
# gh repo delete Ibraheemolasupogit/MS-Fabric-Essentials-Workshop --yes
# gh repo delete Ibraheemolasupogit/mslearn-ai-document-intelligence-102 --yes
# gh repo delete Ibraheemolasupogit/mslearn-ai-fundamentals-AI-900T00-A-Introduction-to-AI-in-Azure --yes
# gh repo delete Ibraheemolasupogit/mslearn-ai-semantic-kernel --yes
# gh repo delete Ibraheemolasupogit/mslearn-ai-services-102 --yes
# gh repo delete Ibraheemolasupogit/mslearn-aspnet-api-ASP-CoreWeb --yes
# gh repo delete Ibraheemolasupogit/mslearn-azure-developer-204 --yes
# gh repo delete Ibraheemolasupogit/mslearn-copilot-Work-smarter-with-AI-using-Microsoft-Copilot-AI-3025 --yes
# gh repo delete Ibraheemolasupogit/mslearn-copilotstudio-copilot --yes
# gh repo delete Ibraheemolasupogit/mslearn-develop-oop-csharp --yes
# gh repo delete Ibraheemolasupogit/mslearn-github-copilot-dev-Accelerate --yes
# gh repo delete Ibraheemolasupogit/mslearn-github-GH-900-100-200-300-500 --yes
# gh repo delete Ibraheemolasupogit/mslearn-mlops_AI-300 --yes
# gh repo delete Ibraheemolasupogit/mslearn-openai-AI-102 --yes
# gh repo delete Ibraheemolasupogit/mslearn-postgresql --yes
# gh repo delete Ibraheemolasupogit/mslearn-sql-dev --yes
# gh repo delete Ibraheemolasupogit/mslearn-sql-developer-DP-800 --yes
# gh repo delete Ibraheemolasupogit/mslearn-sql-migration-DP-3001-Migrate-SQL-Server-workload-to-Azure-SQL --yes
# gh repo delete Ibraheemolasupogit/Multi-Agent-Custom-Automation-Engine-Solution-Accelerator --yes
# gh repo delete Ibraheemolasupogit/Multi-Agent-Trip-Planning-System-google-adk-workflows --yes
# gh repo delete Ibraheemolasupogit/nanoVLM --yes
# gh repo delete Ibraheemolasupogit/NeMo-Guardrails --yes
# gh repo delete Ibraheemolasupogit/NHS-commercial-data-healthcare-predictions --yes
# gh repo delete Ibraheemolasupogit/NHS-DNAproject-showupforhealth --yes
# gh repo delete Ibraheemolasupogit/NHS-GeneralPracticePatientSurvey --yes
# gh repo delete Ibraheemolasupogit/nhs-r-community --yes
# gh repo delete Ibraheemolasupogit/NHS-skunkworks --yes
# gh repo delete Ibraheemolasupogit/NHSR-way --yes
# gh repo delete Ibraheemolasupogit/NHSRwaitinglist --yes
# gh repo delete Ibraheemolasupogit/nhsx-internship-projects --yes
# gh repo delete Ibraheemolasupogit/nltk --yes
# gh repo delete Ibraheemolasupogit/online_payment_fraud --yes
# gh repo delete Ibraheemolasupogit/open-optimization-or-examples --yes
# gh repo delete Ibraheemolasupogit/openai-agents-python --yes
# gh repo delete Ibraheemolasupogit/openai-vision --yes
# gh repo delete Ibraheemolasupogit/OpenAIWorkshop --yes
# gh repo delete Ibraheemolasupogit/PL-200-Power-Platform-Functional-Consultant_Powerapps --yes
# gh repo delete Ibraheemolasupogit/PL-30-PL-300T00-A-Design-and-manage-analytics-solutions-using-Power-BI-DP-605T00 --yes
# gh repo delete Ibraheemolasupogit/PL-400_Microsoft-Power-Platform-Developer --yes
# gh repo delete Ibraheemolasupogit/PL-7001-Create-and-manage-canvas-apps-with-Power-Apps --yes
# gh repo delete Ibraheemolasupogit/PL-7002-Create-and-Manage-Automated-Processes-by-using-Power-Automate --yes
# gh repo delete Ibraheemolasupogit/PL-7003-Create-and-manage-model-driven-apps-with-Power-Apps-and-Dataverse --yes
# gh repo delete Ibraheemolasupogit/postgres --yes
# gh repo delete Ibraheemolasupogit/power-grid-model --yes
# gh repo delete Ibraheemolasupogit/Power-system-stability-PSS-ML --yes
# gh repo delete Ibraheemolasupogit/PowerBI-connector --yes
# gh repo delete Ibraheemolasupogit/predict-customer-churn --yes
# gh repo delete Ibraheemolasupogit/Predictive-Maintenance-of-Aircraft-Engine --yes
# gh repo delete Ibraheemolasupogit/predictive-maintenance-showcase --yes
# gh repo delete Ibraheemolasupogit/ProcessMining --yes
# gh repo delete Ibraheemolasupogit/prompt-flow-labs --yes
# gh repo delete Ibraheemolasupogit/python-debugging-vscode --yes
# gh repo delete Ibraheemolasupogit/pytorch-CycleGAN-and-pix2pix-GAN --yes
# gh repo delete Ibraheemolasupogit/PyTorch-GAN --yes
# gh repo delete Ibraheemolasupogit/pytorch-pretrained-BigGAN --yes
# gh repo delete Ibraheemolasupogit/PyTorch-VAE --yes
# gh repo delete Ibraheemolasupogit/ragflow --yes
# gh repo delete Ibraheemolasupogit/redbox --yes
# gh repo delete Ibraheemolasupogit/sagemaker-ml-workflow-with-apache-airflow --yes
# gh repo delete Ibraheemolasupogit/Sagemaker-studio-lab-examples- --yes
# gh repo delete Ibraheemolasupogit/sample-amazon-redshift-MCP-server --yes
# gh repo delete Ibraheemolasupogit/SC-100-Microsoft-Cybersecurity-Architect --yes
# gh repo delete Ibraheemolasupogit/SC-300-Identity-and-Access-Administrator --yes
# gh repo delete Ibraheemolasupogit/SC-401T00-Information-Security-Administrator --yes
# gh repo delete Ibraheemolasupogit/SC-5003_Information-protection-and-Data-Loss-Prevention --yes
# gh repo delete Ibraheemolasupogit/SC-5007-Implement-retention-eDiscovery-and-Communication-compliance-in-Microsoft-Purview --yes
# gh repo delete Ibraheemolasupogit/SC-5008-Configure-and-manage-entitlement-with-Microsoft-Entra-ID --yes
# gh repo delete Ibraheemolasupogit/SC-900-Microsoft-Security-Compliance-and-Identity-Fundamentals --yes
# gh repo delete Ibraheemolasupogit/scikit-learn --yes
# gh repo delete Ibraheemolasupogit/scikit-survival-Analysis --yes
# gh repo delete Ibraheemolasupogit/scipy --yes
# gh repo delete Ibraheemolasupogit/Secure-Azure-with-Microsoft-Defender-Cloud-Compliance-Controls --yes
# gh repo delete Ibraheemolasupogit/Secure-storage-for-Azure-Files-and-Azure-Blob-Storage --yes
# gh repo delete Ibraheemolasupogit/Security-Copilot --yes
# gh repo delete Ibraheemolasupogit/sfquickstarts --yes
# gh repo delete Ibraheemolasupogit/Simple-DevOps-Project --yes
# gh repo delete Ibraheemolasupogit/skunkworks-adrenal-lesions-detection---computer-vision --yes
# gh repo delete Ibraheemolasupogit/skunkworks-ambulance-queueing-prediction --yes
# gh repo delete Ibraheemolasupogit/skunkworks-bed-allocation --yes
# gh repo delete Ibraheemolasupogit/skunkworks-ct-alignment-lesion-detection-Computer-vision --yes
# gh repo delete Ibraheemolasupogit/skunkworks-data-lens --yes
# gh repo delete Ibraheemolasupogit/skunkworks-long-stayer-risk-stratification --yes
# gh repo delete Ibraheemolasupogit/skunkworks-long-stayer-risk-stratification-baseline --yes
# gh repo delete Ibraheemolasupogit/Smart-Change-Detection-in-Surveillance-Footage --yes
# gh repo delete Ibraheemolasupogit/snowflake-schemachange --yes
# gh repo delete Ibraheemolasupogit/Snowflake-sfguide-getting-started-with-snowpark-for-machine-learning-on-azureml --yes
# gh repo delete Ibraheemolasupogit/spaCy --yes
# gh repo delete Ibraheemolasupogit/spark --yes
# gh repo delete Ibraheemolasupogit/storm --yes
# gh repo delete Ibraheemolasupogit/Structural-Topic-Modelling-for-NHS-survey-datastm-survey-text --yes
# gh repo delete Ibraheemolasupogit/SynthVAE --yes
# gh repo delete Ibraheemolasupogit/terraform-databricks-lakehouse-blueprints --yes
# gh repo delete Ibraheemolasupogit/terraform-provider-databricks --yes
# gh repo delete Ibraheemolasupogit/test-infra --yes
# gh repo delete Ibraheemolasupogit/the-gan-zoo-GAN --yes
# gh repo delete Ibraheemolasupogit/the-turing-way --yes
# gh repo delete Ibraheemolasupogit/ThePhish --yes
# gh repo delete Ibraheemolasupogit/Time_Series_Forecasting_MS --yes
# gh repo delete Ibraheemolasupogit/Titanic-Dataset-Prediction --yes
# gh repo delete Ibraheemolasupogit/tnm-stage-classifier --yes
# gh repo delete Ibraheemolasupogit/training-data-analyst --yes
# gh repo delete Ibraheemolasupogit/transaction-fraud-detection --yes
# gh repo delete Ibraheemolasupogit/transformers --yes
# gh repo delete Ibraheemolasupogit/udemy-aws-de-labs --yes
# gh repo delete Ibraheemolasupogit/UK-HDR-hackathon-projects-2025 --yes
# gh repo delete Ibraheemolasupogit/URLhaus --yes
# gh repo delete Ibraheemolasupogit/using-bedrock-guardrails-with-bedrock-agents-to-improve-adversarial-robustness --yes
# gh repo delete Ibraheemolasupogit/venice --yes
# gh repo delete Ibraheemolasupogit/vertex-ai-creative-studio --yes
# gh repo delete Ibraheemolasupogit/vertex-ai-samples --yes
# gh repo delete Ibraheemolasupogit/vertex-pipelines-end-to-end-samples --yes
# gh repo delete Ibraheemolasupogit/Vision-Language-Models-Overview --yes
# gh repo delete Ibraheemolasupogit/vprofile-project --yes
# gh repo delete Ibraheemolasupogit/Vue.js-core --yes
# gh repo delete Ibraheemolasupogit/website --yes
# gh repo delete Ibraheemolasupogit/whylogs --yes
