"""Dataset schema definitions for synthetic telemetry outputs."""

from __future__ import annotations

DATASET_FILENAMES = {
    "identity_events": "identity_events.jsonl",
    "login_events": "login_events.jsonl",
    "endpoint_events": "endpoint_events.jsonl",
    "application_events": "application_events.jsonl",
    "security_alerts": "security_alerts.jsonl",
    "cloud_activity": "cloud_activity.jsonl",
}

REQUIRED_FIELDS = {
    "identity_events": [
        "event_id",
        "timestamp",
        "user_id",
        "user_principal_name",
        "department",
        "role",
        "event_type",
        "source_system",
        "risk_hint",
        "location",
        "metadata",
    ],
    "login_events": [
        "event_id",
        "timestamp",
        "user_id",
        "user_principal_name",
        "ip_address",
        "country",
        "city",
        "device_id",
        "auth_method",
        "login_status",
        "failure_reason",
        "risk_hint",
        "metadata",
    ],
    "endpoint_events": [
        "event_id",
        "timestamp",
        "device_id",
        "hostname",
        "user_id",
        "process_name",
        "event_type",
        "severity",
        "risk_hint",
        "metadata",
    ],
    "application_events": [
        "event_id",
        "timestamp",
        "application_name",
        "user_id",
        "user_principal_name",
        "event_type",
        "resource",
        "action",
        "severity",
        "risk_hint",
        "metadata",
    ],
    "security_alerts": [
        "alert_id",
        "timestamp",
        "alert_name",
        "severity",
        "entity_type",
        "entity_id",
        "user_id",
        "description",
        "mitre_tactic",
        "mitre_technique",
        "status",
        "risk_hint",
        "metadata",
    ],
    "cloud_activity": [
        "event_id",
        "timestamp",
        "subscription_id",
        "resource_group",
        "resource_type",
        "resource_name",
        "operation_name",
        "caller",
        "result",
        "severity",
        "risk_hint",
        "metadata",
    ],
}

